### ISSUE TITLE
python: upload nightly wheels for testing

### ISSUE THREAD

**Issue by jorisvandenbossche** [apache/arrow-nanoarrow#427]
We already build python wheels every commit on main (plus weekly): https://github.com/apache/arrow-nanoarrow/blob/main/.github/workflows/python-wheels.yaml

It would be nice to upload them to a PyPI index to allow for easier testing, similarly as we do for pyarrow (https://arrow.apache.org/docs/dev/developers/python.html#installing-nightly-packages)

For Arrow, it seems this upload happens through `github_upload_gemfury` macro: https://github.com/apache/arrow/blob/b842b530d14a752697f4283c33f16f2f293713ff/dev/tasks/macros.jinja#L147-L181

I suppose we can more or less copy this approach, which would require setting up an equivalent of `CROSSBOW_GEMFURY_TOKEN` secret for this repo.

**Comment by raulcd** [comment]
I've sent a token to Apache INFRA to add a new secret `NANOARROW_GEMFURY_TOKEN` for Gemfury. Related JIRA issue: https://issues.apache.org/jira/browse/INFRA-25717
